language: python
python:
  - "3.5"

cache:
  - pip

install:
  - pip3 install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd)
  
jobs:
  include:
  	- stage: test
  	script: py.test -v --color=yes
  	- 
  	script: sleep
	- stage: deploy 
	script: bash etc/deploy_docs.sh
	on: 
	  branch: master

after_success:
  - codecov
    

