language: python
python:
  - "3.5"

cache:
  - pip

install:
  - pip3 install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - py.test -v --color=yes

after_success:
  - codecov

deploy:
  skip_cleanup: true
  provider: script
  script: bash etc/deploy_docs.sh
  on:
    branch: master

