language: python

python:
  - 3.5

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest tests.py --cov=.
  - py.test code/* --cov=.

after_success:
  - codecov
